### ISSUE TITLE
example.env Specke server url has extra / that need to be removed.

### ISSUE THREAD

**Issue by knsolutions** [ocni-dtu/boom-speckle#11]
Env parameter is currently that alteres auth path so it doesn´t seem to work:
VITE_APP_SERVER_URL=https://speckle.xyz/ 

Should be:
VITE_APP_SERVER_URL=https://speckle.xyz

Additional note the naming could be more clear VITE_APP_SERVER_URL -> VITE_APP_SPECKLE_SERVER_URL

**Comment by ocni-dtu** [comment]
Great catch!

I actually think we should rename it too `VITE_SPECKLE_SERVER_URL`

**Comment by ocni-dtu** [comment]
Likewise we should rename:

`VITE_APP_APP_ID` -> `VITE_SPECKLE_APP_ID`
`VITE_APP_APP_SECRET` -> `VITE_SPECKLE_APP_SECRET`
